version: 2

updates:
  - package-ecosystem: npm
    directories:
      - /extension
      - /worker
    schedule:
      interval: weekly
    groups:
      npm-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: /extension
    schedule:
      interval: weekly
    versioning-strategy: increase
    groups:
      python-build-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

